"""add created_at to folders

Revision ID: 6f4f69afd0c2
Revises: 
Create Date: 2026-07-30 23:59:39.492002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f4f69afd0c2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=False))
    op.add_column('documents', sa.Column('mime_type', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('extracted', sa.Boolean(), nullable=False))
    op.add_column('documents', sa.Column('text_path', sa.String(length=500), nullable=True))
    op.add_column('documents', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('documents', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('documents', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('documents', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('documents', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_documents_folder_id'), 'documents', ['folder_id'], unique=False)
    op.create_index(op.f('ix_documents_title'), 'documents', ['title'], unique=False)
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.drop_constraint(op.f('documents_user_id_fkey'), 'documents', type_='foreignkey')
    op.drop_constraint(op.f('documents_folder_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'folders', ['folder_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'documents', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('documents', 'last_page')
    op.drop_column('documents', 'uploaded_at')
    op.alter_column('flashcards', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('flashcards', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_flashcards_document_id'), 'flashcards', ['document_id'], unique=False)
    op.create_index(op.f('ix_flashcards_id'), 'flashcards', ['id'], unique=False)
    op.create_index(op.f('ix_flashcards_user_id'), 'flashcards', ['user_id'], unique=False)
    op.drop_constraint(op.f('flashcards_user_id_fkey'), 'flashcards', type_='foreignkey')
    op.drop_constraint(op.f('flashcards_document_id_fkey'), 'flashcards', type_='foreignkey')
    op.create_foreign_key(None, 'flashcards', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'flashcards', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.add_column('folders', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('folders', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_folders_user_id'), 'folders', ['user_id'], unique=False)
    op.create_unique_constraint('uq_user_folder_name', 'folders', ['user_id', 'name'])
    op.drop_constraint(op.f('folders_user_id_fkey'), 'folders', type_='foreignkey')
    op.create_foreign_key(None, 'folders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('quizzes', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('quizzes', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_quizzes_document_id'), 'quizzes', ['document_id'], unique=False)
    op.create_index(op.f('ix_quizzes_id'), 'quizzes', ['id'], unique=False)
    op.drop_constraint(op.f('quizzes_document_id_fkey'), 'quizzes', type_='foreignkey')
    op.create_foreign_key(None, 'quizzes', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.alter_column('summaries', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('summaries', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_summaries_document_id'), 'summaries', ['document_id'], unique=False)
    op.create_index(op.f('ix_summaries_id'), 'summaries', ['id'], unique=False)
    op.create_index(op.f('ix_summaries_user_id'), 'summaries', ['user_id'], unique=False)
    op.drop_constraint(op.f('summaries_document_id_fkey'), 'summaries', type_='foreignkey')
    op.drop_constraint(op.f('summaries_user_id_fkey'), 'summaries', type_='foreignkey')
    op.create_foreign_key(None, 'summaries', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'summaries', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_progress', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'user_progress', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_progress', type_='unique')
    op.alter_column('user_progress', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'summaries', type_='foreignkey')
    op.drop_constraint(None, 'summaries', type_='foreignkey')
    op.create_foreign_key(op.f('summaries_user_id_fkey'), 'summaries', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('summaries_document_id_fkey'), 'summaries', 'documents', ['document_id'], ['id'])
    op.drop_index(op.f('ix_summaries_user_id'), table_name='summaries')
    op.drop_index(op.f('ix_summaries_id'), table_name='summaries')
    op.drop_index(op.f('ix_summaries_document_id'), table_name='summaries')
    op.alter_column('summaries', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('summaries', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.create_foreign_key(op.f('quizzes_document_id_fkey'), 'quizzes', 'documents', ['document_id'], ['id'])
    op.drop_index(op.f('ix_quizzes_id'), table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_document_id'), table_name='quizzes')
    op.alter_column('quizzes', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('quizzes', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'folders', type_='foreignkey')
    op.create_foreign_key(op.f('folders_user_id_fkey'), 'folders', 'users', ['user_id'], ['id'])
    op.drop_constraint('uq_user_folder_name', 'folders', type_='unique')
    op.drop_index(op.f('ix_folders_user_id'), table_name='folders')
    op.alter_column('folders', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('folders', 'created_at')
    op.drop_constraint(None, 'flashcards', type_='foreignkey')
    op.drop_constraint(None, 'flashcards', type_='foreignkey')
    op.create_foreign_key(op.f('flashcards_document_id_fkey'), 'flashcards', 'documents', ['document_id'], ['id'])
    op.create_foreign_key(op.f('flashcards_user_id_fkey'), 'flashcards', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_flashcards_user_id'), table_name='flashcards')
    op.drop_index(op.f('ix_flashcards_id'), table_name='flashcards')
    op.drop_index(op.f('ix_flashcards_document_id'), table_name='flashcards')
    op.alter_column('flashcards', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('flashcards', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('documents', sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('last_page', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_folder_id_fkey'), 'documents', 'folders', ['folder_id'], ['id'])
    op.create_foreign_key(op.f('documents_user_id_fkey'), 'documents', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_title'), table_name='documents')
    op.drop_index(op.f('ix_documents_folder_id'), table_name='documents')
    op.alter_column('documents', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('documents', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('documents', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('documents', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('documents', 'created_at')
    op.drop_column('documents', 'text_path')
    op.drop_column('documents', 'extracted')
    op.drop_column('documents', 'mime_type')
    op.drop_column('documents', 'file_size')
    # ### end Alembic commands ###
